org:
app:
service: toby

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  off:
    handler: switches.off
    events:
      - http:
          path: /hello
          method: get
          cors: true
          private: true

  on:
    handler: switches.on
