org:
app:
service: toby

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  toby:
    handler: handler.toby_handler
    environment:
      discord_oauth_token: ${ssm:/discord/bots/toby/secrets/oauth_token}
